# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hjxx7BMbgyX9aJw3nZl2TgLuWCLn4ME2
"""

!pip install fredapi

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from fredapi import Fred

from pandas.io.parsers import TextFileReader
import requests
from bs4 import BeautifulSoup
import re


url = "https://stableinvestor.com/2021/10/rbi-repo-rate-history-india.html"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.11"
}

soup = BeautifulSoup(response.text, 'html.parser')

records = []

for li in soup.find_all('li'):
    text = li.get_text().strip()

    if 'RBI Repo Rate on' not in text:
        continue

    text = text.replace('RBI Repo Rate on ', '')

    if 'was:' in text:
        parts = text.split('was:')
    else:
        parts = text.split(':', 1)

    if len(parts) != 2:
        continue

    date_str = parts[0].strip()
    rate_str  = parts[1].strip()

    rate_match = re.search(r'[\d.]+', rate_str)

    if rate_match:
        rate = float(rate_match.group())
        records.append({'Date': date_str, 'Repo_Rate': rate})

print(f"✅ Found {len(records)} records")
print("Sample:", records[:3])

from datetime import datetime, timedelta

df = pd.DataFrame(records)

df['Date'] = pd.to_datetime(df['Date'], dayfirst=True, errors='coerce')

df = df.dropna(subset=['Date'])

df = df.sort_values('Date').reset_index(drop=True)

five_years_ago = datetime.today() - timedelta(days=5*365)

df_5yr = df[df['Date'] >= five_years_ago].reset_index(drop=True)

print(f"📅 Full dataset: {df['Date'].min().year} to {df['Date'].max().year} ({len(df)} records)")
print(f"📅 Last 5 years: {len(df_5yr)} MPC meeting records\n")
print(df_5yr.to_string(index=False))

fig, ax = plt.subplots(figsize=(14, 7))

# --- Remove top & right borders (cleaner look) ---
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
ax.spines['left'].set_color('#dddddd')
ax.spines['bottom'].set_color('#dddddd')

# --- Colored phase bands ---
phases = [
    ('2021-02-05', '2022-04-08', '#1a73e8', 'COVID-era hold · 4%'),
    ('2022-04-08', '2023-02-08', '#e53935', 'Hike cycle'),
    ('2023-02-08', '2025-02-07', '#f59300', 'Pause · 6.5%'),
    ('2025-02-07', df_5yr['Date'].max(), '#1e8c5e', 'Easing'),
]
for start, end, color, label in phases:
    ax.axvspan(pd.to_datetime(start), pd.to_datetime(end),
               alpha=0.07, color=color, label=label)

# --- Step line ---
ax.step(df_5yr['Date'], df_5yr['Repo_Rate'],
        where='post', color='#185FA5', linewidth=2.5, zorder=3)

# --- Dots only where rate CHANGED ---
changed = df_5yr[df_5yr['Repo_Rate'] != df_5yr['Repo_Rate'].shift()]
ax.scatter(changed['Date'], changed['Repo_Rate'],
           color='white', edgecolors='#185FA5',
           s=70, linewidth=2, zorder=5)

# --- Fill under line ---
ax.fill_between(df_5yr['Date'], df_5yr['Repo_Rate'],
                step='post', alpha=0.07, color='#185FA5')

# --- Annotate rate change points ---
prev_rate = None
for _, row in changed.iterrows():
    if prev_rate is not None:
        diff = row['Repo_Rate'] - prev_rate
        symbol = f"+{diff:.2f}%" if diff > 0 else f"{diff:.2f}%"
        color  = '#e53935' if diff > 0 else '#1e8c5e'
        ax.annotate(symbol,
                    xy=(row['Date'], row['Repo_Rate']),
                    xytext=(0, 14), textcoords='offset points',
                    ha='center', fontsize=8.5,
                    color=color, fontweight='bold')
    prev_rate = row['Repo_Rate']

# --- Latest rate callout ---
latest_date = df_5yr['Date'].iloc[-1]
latest_rate = df_5yr['Repo_Rate'].iloc[-1]
ax.scatter(latest_date, latest_rate,
           color='#e53935', s=100, zorder=6)
ax.annotate(f"  Current: {latest_rate}%",
            xy=(latest_date, latest_rate),
            fontsize=11, color='#e53935', fontweight='bold', va='center')

# --- Titles & Labels ---
today_str = datetime.today().strftime("%d %b %Y")
ax.set_title("RBI Policy Repo Rate · MPC Meeting History",
             fontsize=15, fontweight='bold', pad=18, loc='left')
ax.set_xlabel("")
ax.set_ylabel("Repo Rate (%)", fontsize=11, color='#555')
ax.tick_params(colors='#777', labelsize=10)

# --- Phase legend (top right) ---
handles = [plt.Rectangle((0,0),1,1, color=c, alpha=0.3)
           for _, _, c, _ in phases]
labels_list = [l for _, _, _, l in phases]
ax.legend(handles, labels_list,
          loc='upper right', fontsize=9,
          framealpha=0.9, edgecolor='#ddd')

# --- Grid & formatting ---
ax.yaxis.grid(True, linestyle='--', alpha=0.4, color='#aaa')
ax.xaxis.grid(False)
ax.set_facecolor('#fafafa')
fig.patch.set_facecolor('white')
ax.xaxis.set_major_formatter(mdates.DateFormatter('%b %Y'))
ax.xaxis.set_major_locator(mdates.MonthLocator(interval=4))
plt.xticks(rotation=45)

# --- Footer ---
fig.text(0.01, -0.03,
         f"Source: RBI via StableInvestor.com  ·  Auto-updated  ·  As of {today_str}",
         fontsize=9, color='#999')

plt.tight_layout()
plt.savefig('rbi_repo_rate.png', dpi=150, bbox_inches='tight')
plt.show()

